#!/usr/bin/env bash
# This script configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Remplace localhost par 127.0.0.2
sudo sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

# Ajoute ou remplace facebook.com → 8.8.8.8
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
